framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@refuge-enkidou.com'
        headers:
            From: 'Le Refuge d''Enkidou <noreply@refuge-enkidou.com>'